sevgenn_flask_blog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    body = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

sevgenn_flask_blog/main/routes.py
from flask import Blueprint, render_template

from sevgenn_flask_blog.models import User

main = Blueprint('main', __name__, template_folder='templates')


@main.route('/')
@main.route('/home')
def home():
    return render_template('home.html', title='Home page')

sevgenn_flask_blog/posts/routes.py
from flask import Blueprint, request, render_template, flash, redirect, \
    url_for, abort
from flask_login import login_required, current_user

from sevgenn_flask_blog.models import Post
from sevgenn_flask_blog.posts.forms import PostForm
from sevgenn_flask_blog import db

posts = Blueprint('posts', __name__)


@posts.route('/allposts')
@login_required
def allposts():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.created.desc()).paginate(page=page,
                                                              per_page=5)
    return render_template('allposts.html', title='Posts', posts=posts)


@posts.route('/post.new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, body=form.title.data,
                    author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post was created!', 'success')
        return redirect(url_for('posts.allposts'))
    return render_template('create_post.html', title='New Post', form=form,
                           legend='New Post')


@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title='post.title', post=post)


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.body = form.body.data
        db.session.commit()
        flash('Your post was updated', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.body.data = post.body
    return render_template('create_post.html', title='Update Post', form=form,
                           legend='Update Post')


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post was deleted', 'success')
    return redirect(url_for('posts.allposts'))

sevgenn_flask_blog/users/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import login_required, current_user, login_user, logout_user

from sevgenn_flask_blog import db, bcrypt
from sevgenn_flask_blog.users.forms import RegistrationForm, LoginForm, \
    UpdateAccountForm, RequestResetForm, ResetPasswordForm
from sevgenn_flask_blog.models import User, Post
from sevgenn_flask_blog.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__, template_folder='templates')


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data,
                    password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in',
              'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Registration', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('posts.allposts'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password,
                                               form.password.data):
            login_user(user, remember=form.remember.data)

            next_page = request.args.get('next')
            if next_page:
                return redirect(next_page)
            else:
                return redirect(url_for('posts.allposts'))
        else:
            flash('Login failed. Please, check email and password.', 'danger')
    return render_template('login.html', title='Authentication', form=form)


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form_picture=form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account was successfully updated', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        page = request.args.get('page', 1, type=int)
        user = User.query.filter_by(username=form.username.data).first_or_404()
        posts = Post.query.filter_by(author=user).order_by(
            Post.created.desc()).paginate(page=page, per_page=5)
        image_file = url_for('static',
                             filename='pictures/' + current_user.image_file)
        return render_template('account.html', title='Account',
                               image_file=image_file, form=form, posts=posts,
                               user=user)


@users.route('/logout')
def logout():
    print(current_user)
    logout_user()
    return redirect(url_for('main.home'))


@users.route('/user/<string:username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(
        Post.created.desc()).paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('posts.allposts'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('A letter with instructions was sent to the mail', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Password Reset',
                           form=form)


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('posts.allposts'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Invalid or expired token', 'danger')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated!', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Password Reset',
                           form=form)

sevgenn_flask_blog/templates/account.html
{% extends "base.html" %}

{% block style %}
  <style>
    .container{
      margin-bottom: 0.8rem;
    }

    .content-section{
      box-shadow: 10px 20px 8px darkslategray;
    }

    .card{
      border-radius: 25px;
      /* border-top-right-radius: 25px;
      border-bottom-left-radius: 25px; */
      background-color:  white; 
      box-shadow: 10px 15px 10px #4a4e69;
      width: 92%;
    }

    a{
      color: #003049;
    }

    small{
      color: lightslategray;
    }

    p{
      color: rgb(43, 37, 37);
    }
    
    /* i{
      padding: 0px 7px;
      cursor: pointer;
    } */
  </style>
{% endblock %}


{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>

      <form method="POST" action="" enctype="multipart/form-data">
          {{ form.hidden_tag() }}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Аккаунт пользователя</legend>
              <div class="form-group">
                  {{ form.username.label(class="form-control-label") }}

                  {% if form.username.errors %}
                      {{ form.username(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in form.username.errors %}
                              <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                  {% else %}
                      {{ form.username(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
              <div class="form-group my-3">
                  {{ form.email.label(class="form-control-label") }}
                  {% if form.email.errors %}
                      {{ form.email(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in form.email.errors %}
                              <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                  {% else %}
                      {{ form.email(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
              <div class="form-group my-3">
                  {{ form.picture.label() }}
                  {{ form.picture(class="form-control-file") }}
                  {% if form.picture.errors %}
                      {% for error in form.picture.errors %}
                          <span class="text-danger">{{ error }}</span></br>
                      {% endfor %}
                  {% endif %}
              </div>
          </fieldset>
          <div class="form-group my-3">
              {{ form.submit(class="btn btn-outline-info") }}
          </div>
      </form>      
    </div>   



{% endblock %}

sevgenn_flask_blog/templates/allposts.html
{% extends "base.html" %}

{% block content %}
  {% for post in posts.items %}
  <div class="container" style="display: flex;">
    <article class="media col-1" style="display: flex; flex-direction: column;">
      <img class="rounded-circle article-img" style="margin-right: 5px;" src="{{ url_for('static', filename='pictures/' + post.author.image_file) }}">
      <a href="{{ url_for('users.user_posts', username=post.author.username) }}" id="author" style="margin: 0 auto;">{{ post.author.username }}</a>
    </article>
    
    <div class="card col-6 offset-1" style="margin-bottom: 20px;">
      <div class="card-body">
        <h4 class="card-title"><a class="title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h4>

        <small>Posted {{ post.created.strftime('%A, %d %B %Y %I:%M %p') }}</small>
        <br>
        <br>
        <p class="card-text">{{ post.body }}</p>
      </div>
      <!-- <div class="card-footer" style="font-size: 20px;">
        <i class="fa fa-heart-o"></i>
        <i class="fa fa-bookmark-o"></i>
      </div> -->
    </div>
  </div>
  {% endfor %}

  {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
      {% if posts.page == page_num %}
        <a class="btn btn-success mb-4 col-1 mx-2" href="{{ url_for('posts.allposts', page=page_num) }}">{{ page_num }}</a>
      {% else %}
        <a class="btn btn-outline-success mb-4 col-1 mx-2" href="{{ url_for('posts.allposts', page=page_num) }}">{{ page_num }}</a>
      {% endif %}
    {% else %}
      ...
    {% endif %}
  {% endfor %}
{% endblock %}

sevgenn_flask_blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        Flask-blog |
        {% block title %}
            {{ title }}
        {% endblock title %}
    </title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">

    {% block style %}
    {% endblock style %}
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
          <a class="navbar-brand" href="{{ url_for('main.home') }}">Home</a>
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{ url_for('users.user_posts', username=current_user.username) }}">
                <span>
                  {% if current_user.is_authenticated %}
                    {{ current_user.username | title }}'s
                  {% else %}
                    Guest's
                  {% endif %}
              </span>Blog</a>
            </li>
          </ul>

          <div class="collapse navbar-collapse">
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-primary" type="submit">Search</button>
            </form>
          </div>

          <div class="navbar-right">
            <a class="nav-link" href="#" style="color: white">Admin</a>
          </div>

          <div class="navbar-right">
            <div class="navbar-collapse">
              {% if current_user.is_authenticated %}
                <a class="nav-link" href="{{ url_for('users.account') }}" style="color: white">Profile</a>
                <a class="nav-link" href="{{ url_for('posts.new_post') }}" style="color: white">New post</a>
                <a class="nav-link" href="{{ url_for('posts.allposts') }}" style="color: white">Posts</a>
                <a class="nav-link" href="{{ url_for('users.logout') }}" style="color: white">Log out</a>
              {% else %}
                <a class="nav-link" href="{{ url_for('users.login') }}" style="color: white">Login</a>
                <a class="nav-link" href="{{ url_for('users.register') }}" style="color: white">Registration</a>
              {% endif %}
            </div>
          </div>
        </div>
      </div><!-- container-fluid -->
    </nav>

    <main class="container">
      <div class="row">
        <div class="col-md-10">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
        </div>
      </div>
    
      <div class="row">
        <h1>
            {% block content_title %}
            {% endblock content_title %}
        </h1>
            {% block content %}
            {% endblock content %}
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</html>

sevgenn_flask_blog/templates/create_post.html
{% extends "base.html" %}

{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label my-1") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg my-3") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.body.label(class="form-control-label") }}
                {% if form.body.errors %}
                    {{ form.body(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.body.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.body(class="form-control form-control-lg my-3") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock %}

sevgenn_flask_blog/templates/home.html
{% extends "base.html" %}

{% block content_title %}
    Home page
{% endblock %}

{% block content %}
    <div class="col-md-6 offset-md-3">
        <h3>Добро пожаловать, о повелитель моего свободного времени.</h3>
        <p>Да не устанут твои глаза, и не утомится твой указательный палец
        в путешествиях по этому сайту.</p>
        <p>Да не пробудит в тебе гнев изысканный дизайн сей страницы.
            Homo sum et nihil humanum a me alienum puto.</p>
        <p>Как говорил Заратустра, Lorem ipsum dolor sit amet, consectetur adipisicing elit.
            Alias fuga ipsa nemo placeat repellendus. Corporis esse laborum
            optio repellat vel voluptatem, voluptatum! Adipisci ea eligendi
            illum nam obcaecati repellat vero.</p>
    </div>
{% endblock %}

sevgenn_flask_blog/templates/login.html
{% extends "base.html" %}

{% block content %}
    <div class="content-section" style="box-shadow: 10px 15px 10px #4a4e69;">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Authentication</legend>
                <div class="form-group my-3">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group my-3">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group my-3">
                {{ form.submit(class="btn btn-outline-info") }}

                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot your password?</a>
                </small>
            </div>
            <small style="font-size: 15px; font-weight: 500;">
                <a class="ml-2" href="{{ url_for('users.register') }}">Register</a>
            </small>
        </form>
    </div>
{% endblock %}

sevgenn_flask_blog/templates/post.html
{% extends "base.html" %}

{% block content %}
<div class="container" style="display: flex;">
  <article class="media col-1" style="display: flex; flex-direction: column;">
    <img class="rounded-circle article-img" style="margin-right: 5px;" src="{{ url_for('static', filename='pictures/' + post.author.image_file) }}">
    <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}" style="margin: 0 auto">{{ post.author.username }}</a>
  </article>
  
  <div class="card col-6 offset-1" style="margin-bottom: 20px;">
    <div class="card-body">
      <h4 class="card-title">{{ post.title }}</h4>
      <small>Posted {{ post.created.strftime('%A, %d %B %Y %I:%M %p') }}</small>
      <br>
      <br>
      <p class="card-text">{{ post.body }}</p>
    </div>
    <div class="card-footer" style="font-size: 20px;">
      <!-- <i class="fa fa-heart-o"></i>
      <i class="fa fa-bookmark-o"></i> -->
      {% if post.author == current_user %}
        <div class="card-footer" style="font-size: 20px;">
          <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{url_for('posts.update_post', post_id=post.id) }}">Update</a>
          <button type="button" class="btn btn-danger btn-sm m-1" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>
        </div>
      {% endif %}

    </div>
  </div>
</div>
  
<!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

sevgenn_flask_blog/templates/register.html
{% extends "base.html" %}

{% block content %}
    <div class="content-section" style="box-shadow: 10px 15px 10px #4a4e69;">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Registration</legend>
                <div class="form-group my-3">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group my-3">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group my-3">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group my-3">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group my-3">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock %}

sevgenn_flask_blog/templates/reset_request.html
{% extends "base.html" %}

{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Password Reset</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group my-4">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock %}

sevgenn_flask_blog/templates/user_posts.html
{% extends "base.html" %}

{% block content %}
    <h1 class="mb-3">Посты опубликованы пользователем {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
    <div class="container" style="display: flex;">
      <article class="media col-1" style="display: flex; flex-direction: column;">
        <img class="rounded-circle article-img" style="margin-right: 5px;" src="{{ url_for('static', filename='pictures/' + post.author.image_file) }}">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}" style="margin: 0 auto">{{ post.author.username }}</a>
      </article>
      
      <div class="card col-6 offset-1" style="margin-bottom: 20px;">
        <div class="card-body">
          <h4 class="card-title"><a class="title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h4>

          <small>Posted {{ post.created.strftime('%A, %d %B %Y %I:%M %p') }}</small>
          <br>
          <br>
          <p class="card-text">{{ post.body }}</p>
        </div>
        <!-- <div class="card-footer" style="font-size: 20px;">
          <i class="fa fa-heart-o"></i>
          <i class="fa fa-bookmark-o"></i>
        </div> -->
      </div>
    </div>
    {% endfor %}

    
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-success mb-4 col-1 mx-2" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-success mb-4 col-1 mx-2" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock %}